# Generated by Django 3.2.5 on 2021-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=8, null=True)),
                ('category', models.CharField(choices=[('CUB', 'Underbone'), ('SPO', 'Sport'), ('STR', 'Street'), ('SCO', 'Scooter')], max_length=3, null=True)),
                ('bike_class', models.CharField(choices=[('2B', 'Class 2B'), ('2A', 'Class 2A'), ('2', 'Class 2')], max_length=2, null=True)),
                ('bike_model', models.CharField(choices=[('Aerox', 'Yamaha Aerox 155'), ('Sniper', 'Yamaha Sniper T150'), ('FZ16', 'Yamaha FZ16'), ('FZ16ST', 'Yamaha FZ16ST'), ('CB190R', 'Honda CB190R'), ('CB400 Sp2', 'Honda CB400 (Super 4) Spec 2'), ('CB400 Sp3', 'Honda CB400 (Super 4) Spec 3')], max_length=12, null=True)),
            ],
        ),
    ]
