# Generated by Django 3.2.5 on 2021-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('CUB', 'Underbone'), ('SPO', 'Sport'), ('STR', 'Street')], max_length=3)),
            ],
        ),
    ]
